version: "3.9"
services:
  elasticurl:
    profiles: ["all", "elastic"]
    depends_on:
      - mongodb
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_AUTH_DB: admin
      MONGO_DATASOURCE_USERNAME: root
      MONGO_DATASOURCE_PASSWORD: root
      MONGO_DATASOURCE_DATABASE: shorturl_db
      MONGO_DATASOURCE_PORT: 27017
      MONGO_DATASOURCE_URL: mongodb
    ports:
        - "8080:8080"
  mongodb:
    profiles: ["all", "mongodb"]
    image: mongo:6-jammy
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./init-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
